services:
  app:
    build:
      context: ./backend
      target: builder
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
