services:
  app:
    build:
      context: ./backend
      target: builder
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
